jenkins_home: /var/lib/jenkins

jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_admin_password_file: ""

jenkins_process_user: jenkins
jenkins_process_group: "{{ jenkins_process_user }}"